#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "[WARN] $*"
}

die () {
    echo "Error: $*"
    exit 1
}

# OS specific support (sh)
case "$(uname)" in
  CYGWIN*|MINGW*|MSYS*)
    APP_HOME=$(cygpath -u "$APP_HOME")
    ;;
  *)
    APP_HOME=$(cd "$(dirname "$0")" && pwd)
    ;;
 esac

APP_HOME=$(cd "$APP_HOME" && pwd)

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase the maximum file descriptors if we can.
if [ "$MAX_FD" != "maximum" ] ; then
    MAX_FD="$MAX_FD"
fi

# Escape application args
save () {
    printf '%s\n' "$1" | sed 's/[]\\/.$*^|[]/\\&/g'
}

APP_ARGS=$(save "$@")

# Collect all arguments.
for opt in "$@"; do
    case "$opt" in
        -D*)
            eval "${opt#-D}";
            ;;
        *)
            ;;
    esac
done

# Determine if the Gradle wrapper jar exists.
if [ ! -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    echo "Gradle wrapper jar not found. Please run 'gradle wrapper' or download the wrapper jar manually."
    exit 1
fi

exec "$JAVACMD" -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
